### ISSUE TITLE
draging with look and without look not work only work 3finger darg 

### ISSUE THREAD

**Issue by Edwardwich** [VoodooSMBus/VoodooRMI#186] opened 2024-10-08 15:52 UTC
draging with look and without look not work only work 3finger darg :

VoodooRMI version : 1.4.0
VoodooPS2 version :2.3.6.

![Screenshot 2024-10-08 at 19 18 15](https://github.com/user-attachments/assets/ef9a8545-f010-4cd6-aec1-f4a99912b064)

![Screenshot 2024-10-08 at 19 17 07](https://github.com/user-attachments/assets/90918a27-faae-41cb-9866-d26db8e03125)

sudo dmesg:
[log.txt](https://github.com/user-attachments/files/17295871/log.txt)

iotrg:
[Ali’s MacBook Pro.ioreg.zip](https://github.com/user-attachments/files/17295876/Ali.s.MacBook.Pro.ioreg.zip)

**Comment by 1Revenger1** [comment] 2024-10-08 16:03
How is Drag with or without lock supposed to work? Appears to work on my side on Sonoma - I can double tap the top of the window then start moving it around. It'll stay locked to the window depending on the drag lock setting.

**Comment by Edwardwich** [comment] 2024-10-08 16:24
> How is Drag with or without lock supposed to work? Appears to work on my side on Sonoma - I can double tap the top of the window then start moving it around. It'll stay locked to the window depending on the drag lock setting.

yes in Sonoma work but in sequoia not working

**Comment by Edwardwich** [comment] 2024-10-08 16:25
and also drag with look and without look work in mac os sequoia when useing VoodooRMI version : 1.3.5

**Comment by 1Revenger1** [comment] 2024-10-12 02:52
I do not have a laptop running Sequoia unfortunately, so am unable to reproduce this. Just as a quick sanity check, is tap to click enabled under the Sequoia touchpad settings? I think it is enabled automatically with drag lock but it is probably worth double checking.

Some tests I guess - Can you try just replacing VoodooSMBus with the older version while keeping the newer VoodooRMI?
Second set of sets is trying out a few different commits of VoodooRMI. The ones that make changes to input handling between 1.3.5 and 1.4 is
fb93f3f1b1d4285fca5f9e5b5db6a55979ef5ef3
3f0dd535cb3f347024939dd4f54be4e18a5fb978
e73d53371d97b6c04ae57e2fe73bc10a6010b45c
341ff046ca11aa310187a0dcbf06e047f18e8fae

The different builds of VoodooRMI can be grabbed here: https://dortania.github.io/builds/?product=VoodooRMI&viewall=true

**Comment by Edwardwich** [comment] 2024-10-12 09:01
![Screenshot 2024-10-12 at 12 28 39](https://github.com/user-attachments/assets/365152c6-657b-486f-9040-570e5608fef7)
![Screenshot 2024-10-12 at 12 29 28](https://github.com/user-attachments/assets/6f9d50fb-a1d1-49c6-90a7-fe07444bf9c5)

I try older verions of  VoodooSMBus with last VoodooRMI and tell u

**Comment by Edwardwich** [comment] 2024-10-12 09:20
i try voodoo rmi 1.4.1 with VoodooSMBus 1.3.5 but all gestures is broken 
![Screenshot 2024-10-12 at 12 49 30](https://github.com/user-attachments/assets/3000b747-9414-4e90-8ca6-fd0f1011c946)
and also tap to clik not worl

**Comment by Edwardwich** [comment] 2024-10-12 09:24
![Screenshot 2024-10-12 at 12 54 07](https://github.com/user-attachments/assets/60bb67fa-ceaf-47d6-9745-5584e9e100c8)

**Comment by Edwardwich** [comment] 2024-10-12 09:43
[Ali’s MacBook Pro.ioreg.zip](https://github.com/user-attachments/files/17349542/Ali.s.MacBook.Pro.ioreg.zip)

**Comment by Edwardwich** [comment] 2024-10-12 14:48
> I do not have a laptop running Sequoia unfortunately, so am unable to reproduce this. Just as a quick sanity check, is tap to click enabled under the Sequoia touchpad settings? I think it is enabled automatically with drag lock but it is probably worth double checking.
> 
> Some tests I guess - Can you try just replacing VoodooSMBus with the older version while keeping the newer VoodooRMI? Second set of sets is trying out a few different commits of VoodooRMI. The ones that make changes to input handling between 1.3.5 and 1.4 is [fb93f3f](https://github.com/VoodooSMBus/VoodooRMI/commit/fb93f3f1b1d4285fca5f9e5b5db6a55979ef5ef3) [3f0dd53](https://github.com/VoodooSMBus/VoodooRMI/commit/3f0dd535cb3f347024939dd4f54be4e18a5fb978) [e73d533](https://github.com/VoodooSMBus/VoodooRMI/commit/e73d53371d97b6c04ae57e2fe73bc10a6010b45c) [341ff04](https://github.com/VoodooSMBus/VoodooRMI/commit/341ff046ca11aa310187a0dcbf06e047f18e8fae)
> 
> The different builds of VoodooRMI can be grabbed here: https://dortania.github.io/builds/?product=VoodooRMI&viewall=true

hi I fork ur repo and revert all code in fb93f3f and now every thing work great with last voodoo ps2 kext 

my voodoo rmi repo : https://github.com/Edwardwich/VoodooRMI/tree/fb93f3f

**Comment by 1Revenger1** [comment] 2024-10-12 16:45
[VoodooRMI-1.4.2-DEBUG.zip](https://github.com/user-attachments/files/17350781/VoodooRMI-1.4.2-DEBUG.zip)
Mind giving this a shot?

**Comment by Edwardwich** [comment] 2024-10-12 17:36
> [VoodooRMI-1.4.2-DEBUG.zip](https://github.com/user-attachments/files/17350781/VoodooRMI-1.4.2-DEBUG.zip) Mind giving this a shot?

everything work grate now thank you 
[Ali’s MacBook Pro.ioreg.zip](https://github.com/user-attachments/files/17350898/Ali.s.MacBook.Pro.ioreg.zip)
[Terminal Saved Output.txt](https://github.com/user-attachments/files/17350905/Terminal.Saved.Output.txt)

**Closed** 2024-10-12 17:42 UTC

**Comment by 1Revenger1** [comment] 2024-10-12 17:44
Thanks! I've gone ahead and pushed the changes to master.

**Comment by Edwardwich** [comment] 2024-10-12 19:11
> Thanks! I've gone ahead and pushed the changes to master.

already I download and use it TNX a lot
